
contact:
  linkc: "http://www.railstutorial.org/contact"
_footer:
  linkf1: "https://www.onlinequizcreator.com/"
  linkf2: "https://www.facebook.com/nguyenxuan.tuan.9461"
  linkf3: "https://github.com/awesome-academy/PR1-OE12-Test-Management/pull/1/files"

num_50: 50
num_225: 225
num_6: 6